export function buildCommandRegistry(ctx) {
  const commands = [
    {
      id: 'file.open',
      label: 'Open PDF',
      shortcut: 'Ctrl+O',
      keywords: ['open', 'load', 'import', 'browse'],
      category: 'File',
      execute: () => ctx.handleOpen(),
    },
    {
      id: 'file.save',
      label: 'Save PDF',
      shortcut: 'Ctrl+S',
      keywords: ['save', 'export', 'download', 'write'],
      category: 'File',
      requiresDoc: true,
      execute: () => ctx.handleSave(),
    },
    {
      id: 'file.saveAs',
      label: 'Save As',
      shortcut: 'Ctrl+Shift+S',
      keywords: ['save as', 'export as'],
      category: 'File',
      requiresDoc: true,
      execute: () => ctx.handleSaveAs?.(),
    },
    {
      id: 'file.print',
      label: 'Print PDF',
      shortcut: 'Ctrl+P',
      keywords: ['print'],
      category: 'File',
      requiresDoc: true,
      execute: () => ctx.handlePrint(),
    },
    {
      id: 'edit.undo',
      label: 'Undo',
      shortcut: 'Ctrl+Z',
      keywords: ['undo'],
      category: 'Edit',
      execute: () => ctx.undo(),
    },
    {
      id: 'edit.redo',
      label: 'Redo',
      shortcut: 'Ctrl+Y',
      keywords: ['redo'],
      category: 'Edit',
      execute: () => ctx.redo(),
    },
    {
      id: 'page.insert',
      label: 'Insert Blank Page',
      shortcut: null,
      keywords: ['insert', 'blank', 'new page'],
      category: 'Pages',
      requiresDoc: true,
      execute: () => ctx.handleAddBlank(),
    },
    {
      id: 'page.delete',
      label: 'Delete Current Page',
      shortcut: 'Delete',
      keywords: ['delete page', 'remove page'],
      category: 'Pages',
      requiresDoc: true,
      destructive: true,
      execute: () => ctx.handleDeletePage(),
    },
    {
      id: 'page.rotate',
      label: 'Rotate Page 90',
      shortcut: null,
      keywords: ['rotate', 'turn'],
      category: 'Pages',
      requiresDoc: true,
      execute: () => ctx.handleRotate(90),
    },
    {
      id: 'file.merge',
      label: 'Merge PDF',
      shortcut: null,
      keywords: ['merge', 'combine', 'append'],
      category: 'Pages',
      requiresDoc: true,
      execute: () => ctx.handleMerge(),
    },
    {
      id: 'file.split',
      label: 'Split / Extract Pages',
      shortcut: null,
      keywords: ['split', 'extract', 'range'],
      category: 'Pages',
      requiresDoc: true,
      execute: () => ctx.handleSplit(),
    },
    {
      id: 'tool.select',
      label: 'Select Tool',
      shortcut: 'V',
      keywords: ['select', 'move', 'pointer'],
      category: 'Annotate',
      requiresDoc: true,
      execute: () => ctx.setActiveTool('select'),
    },
    {
      id: 'tool.text',
      label: 'Text Tool',
      shortcut: 'T',
      keywords: ['text', 'type'],
      category: 'Annotate',
      requiresDoc: true,
      execute: () => ctx.setActiveTool('text'),
    },
    {
      id: 'tool.highlight',
      label: 'Highlight Tool',
      shortcut: 'H',
      keywords: ['highlight', 'mark'],
      category: 'Annotate',
      requiresDoc: true,
      execute: () => ctx.setActiveTool('highlight'),
    },
    {
      id: 'tool.draw',
      label: 'Draw Tool',
      shortcut: 'D',
      keywords: ['draw', 'pencil'],
      category: 'Annotate',
      requiresDoc: true,
      execute: () => ctx.setActiveTool('draw'),
    },
    {
      id: 'tool.signature',
      label: 'Signature Tool',
      shortcut: 'S',
      keywords: ['sign', 'signature'],
      category: 'Annotate',
      requiresDoc: true,
      execute: () => ctx.handleToolChange('signature'),
    },
    {
      id: 'tool.redact',
      label: 'Redact Tool',
      shortcut: 'R',
      keywords: ['redact', 'black out'],
      category: 'Annotate',
      requiresDoc: true,
      execute: () => ctx.setActiveTool('redact'),
    },
    {
      id: 'tool.crop',
      label: 'Crop Tool',
      shortcut: 'C',
      keywords: ['crop'],
      category: 'Annotate',
      requiresDoc: true,
      execute: () => ctx.setActiveTool('crop'),
    },
    {
      id: 'tool.edit',
      label: 'Edit Tool',
      shortcut: 'E',
      keywords: ['edit', 'whiteout'],
      category: 'Annotate',
      requiresDoc: true,
      execute: () => ctx.setActiveTool('edit'),
    },
    {
      id: 'arrange.front',
      label: 'Bring to Front',
      shortcut: null,
      keywords: ['front', 'top', 'bring to front'],
      category: 'Arrange',
      requiresDoc: true,
      execute: () => ctx.applyZOrder('front'),
    },
    {
      id: 'arrange.forward',
      label: 'Bring Forward',
      shortcut: null,
      keywords: ['forward', 'bring forward'],
      category: 'Arrange',
      requiresDoc: true,
      execute: () => ctx.applyZOrder('forward'),
    },
    {
      id: 'arrange.backward',
      label: 'Send Backward',
      shortcut: null,
      keywords: ['backward', 'send backward'],
      category: 'Arrange',
      requiresDoc: true,
      execute: () => ctx.applyZOrder('backward'),
    },
    {
      id: 'arrange.back',
      label: 'Send to Back',
      shortcut: null,
      keywords: ['back', 'send to back'],
      category: 'Arrange',
      requiresDoc: true,
      execute: () => ctx.applyZOrder('back'),
    },
    {
      id: 'export.watermark',
      label: 'Toggle Watermark',
      shortcut: null,
      keywords: ['watermark'],
      category: 'Layout',
      requiresDoc: true,
      execute: () => ctx.handleWatermark(),
    },
    {
      id: 'export.word',
      label: 'Export to Word',
      shortcut: null,
      keywords: ['word', 'docx'],
      category: 'Export',
      requiresDoc: true,
      execute: () => ctx.handleExportWord(),
    },
    {
      id: 'file.importImages',
      label: 'Import Images',
      shortcut: null,
      keywords: ['images', 'import', 'place'],
      category: 'File',
      requiresDoc: true,
      execute: () => ctx.handleImportImages(),
    },
    {
      id: 'view.zoom.in',
      label: 'Zoom In',
      shortcut: 'Ctrl+=',
      keywords: ['zoom in'],
      category: 'View',
      requiresDoc: true,
      execute: () => ctx.setZoom(z => Math.min(3, z + 0.25)),
    },
    {
      id: 'view.zoom.out',
      label: 'Zoom Out',
      shortcut: 'Ctrl+-',
      keywords: ['zoom out'],
      category: 'View',
      requiresDoc: true,
      execute: () => ctx.setZoom(z => Math.max(0.25, z - 0.25)),
    },
    {
      id: 'view.commandPalette',
      label: 'Command Palette',
      shortcut: 'Ctrl+K',
      keywords: ['command', 'palette'],
      category: 'View',
      execute: () => ctx.toggleCommandPalette(),
    },
    {
      id: 'page.prev',
      label: 'Previous Page',
      shortcut: null,
      keywords: ['previous', 'page back'],
      category: 'View',
      requiresDoc: true,
      execute: () => ctx.setCurrentPage(p => Math.max(1, p - 1)),
    },
    {
      id: 'page.next',
      label: 'Next Page',
      shortcut: null,
      keywords: ['next', 'page forward'],
      category: 'View',
      requiresDoc: true,
      execute: () => ctx.setCurrentPage(p => Math.min(ctx.numPages, p + 1)),
    },
  ];

  if (import.meta.env?.DEV) {
    commands.push({
      id: 'kernel.health',
      label: 'Kernel Health Check',
      shortcut: null,
      keywords: ['kernel', 'health', 'diagnostics'],
      category: 'Diagnostics',
      execute: () => ctx.runKernelHealthCheck?.(),
    });
  }

  return commands;
}
