export const COMMAND_REGISTRY = [
  {
    id: 'tool.select',
    label: 'Select Tool',
    keywords: ['select', 'move', 'pointer', 'arrow'],
    category: 'Tools',
    icon: 'MousePointer',
    shortcut: 'V',
    execute: ({ setActiveTool }) => setActiveTool('select'),
  },
  {
    id: 'tool.text',
    label: 'Add Text Box',
    keywords: ['text', 'type', 'write', 'label'],
    category: 'Tools',
    icon: 'Type',
    shortcut: 'T',
    execute: ({ setActiveTool }) => setActiveTool('text'),
  },
  {
    id: 'tool.highlight',
    label: 'Highlight',
    keywords: ['highlight', 'mark', 'emphasize'],
    category: 'Tools',
    icon: 'Highlighter',
    shortcut: 'H',
    execute: ({ setActiveTool }) => setActiveTool('highlight'),
  },
  {
    id: 'tool.redact',
    label: 'Redact (Black Out)',
    keywords: ['redact', 'black out', 'censor', 'hide'],
    category: 'Tools',
    icon: 'ShieldOff',
    execute: ({ setActiveTool }) => setActiveTool('redact'),
  },
  {
    id: 'tool.signature',
    label: 'Add Signature',
    keywords: ['sign', 'signature', 'esign', 'initial'],
    category: 'Tools',
    icon: 'PenTool',
    execute: ({ setActiveTool, signatureDataUrl, setShowSignaturePad }) => {
      if (!signatureDataUrl) setShowSignaturePad(true);
      else setActiveTool('signature');
    },
  },
  {
    id: 'page.rotate.cw',
    label: 'Rotate Page Clockwise',
    keywords: ['rotate', 'turn', 'cw', 'clockwise', 'landscape'],
    category: 'Page',
    icon: 'RotateCw',
    execute: ({ handleRotate }) => handleRotate(90),
    requiresDoc: true,
  },
  {
    id: 'page.delete',
    label: 'Delete Current Page',
    keywords: ['delete page', 'remove page'],
    category: 'Page',
    icon: 'Trash2',
    execute: ({ handleDeletePage }) => handleDeletePage(),
    requiresDoc: true,
    destructive: true,
  },
  {
    id: 'page.add',
    label: 'Insert Blank Page',
    keywords: ['add page', 'blank', 'new page', 'insert'],
    category: 'Page',
    icon: 'FilePlus',
    execute: ({ handleAddBlank }) => handleAddBlank(),
    requiresDoc: true,
  },
  {
    id: 'file.open',
    label: 'Open PDF',
    keywords: ['open', 'load', 'import', 'browse'],
    category: 'File',
    icon: 'FolderOpen',
    shortcut: 'Ctrl+O',
    execute: ({ handleOpen }) => handleOpen(),
  },
  {
    id: 'file.save',
    label: 'Save PDF',
    keywords: ['save', 'export', 'download', 'write'],
    category: 'File',
    icon: 'Save',
    shortcut: 'Ctrl+S',
    execute: ({ handleSave }) => handleSave(),
    requiresDoc: true,
  },
  {
    id: 'file.merge',
    label: 'Merge Another PDF',
    keywords: ['merge', 'combine', 'append', 'join'],
    category: 'File',
    icon: 'FileStack',
    execute: ({ handleMerge }) => handleMerge(),
    requiresDoc: true,
  },
  {
    id: 'file.split',
    label: 'Extract Page Range',
    keywords: ['split', 'extract pages', 'range', 'cut'],
    category: 'File',
    icon: 'Scissors',
    execute: ({ handleSplit }) => handleSplit(),
    requiresDoc: true,
  },
  {
    id: 'edit.copy',
    label: 'Copy Selection',
    keywords: ['copy', 'clipboard'],
    category: 'Edit',
    icon: 'MousePointer',
    shortcut: 'Ctrl+C',
    execute: ({ handleCopy }) => handleCopy(),
    requiresDoc: true,
  },
  {
    id: 'edit.paste',
    label: 'Paste',
    keywords: ['paste', 'clipboard'],
    category: 'Edit',
    icon: 'MousePointer',
    shortcut: 'Ctrl+V',
    execute: ({ handlePaste }) => handlePaste(),
    requiresDoc: true,
  },
  {
    id: 'edit.duplicate',
    label: 'Duplicate Selection',
    keywords: ['duplicate', 'copy'],
    category: 'Edit',
    icon: 'MousePointer',
    shortcut: 'Ctrl+D',
    execute: ({ handleDuplicate }) => handleDuplicate(),
    requiresDoc: true,
  },
  {
    id: 'align.left',
    label: 'Align Left',
    keywords: ['align left'],
    category: 'Align',
    icon: 'MousePointer',
    execute: ({ applyAlignment }) => applyAlignment('left'),
    requiresDoc: true,
  },
  {
    id: 'align.center',
    label: 'Align Center Horizontal',
    keywords: ['align center', 'center'],
    category: 'Align',
    icon: 'MousePointer',
    execute: ({ applyAlignment }) => applyAlignment('centerH'),
    requiresDoc: true,
  },
  {
    id: 'align.right',
    label: 'Align Right',
    keywords: ['align right'],
    category: 'Align',
    icon: 'MousePointer',
    execute: ({ applyAlignment }) => applyAlignment('right'),
    requiresDoc: true,
  },
  {
    id: 'align.distribute.h',
    label: 'Distribute Horizontally',
    keywords: ['distribute horizontal'],
    category: 'Align',
    icon: 'MousePointer',
    execute: ({ applyAlignment }) => applyAlignment('distributeH'),
    requiresDoc: true,
  },
  {
    id: 'align.distribute.v',
    label: 'Distribute Vertically',
    keywords: ['distribute vertical'],
    category: 'Align',
    icon: 'MousePointer',
    execute: ({ applyAlignment }) => applyAlignment('distributeV'),
    requiresDoc: true,
  },
  {
    id: 'zorder.front',
    label: 'Bring To Front',
    keywords: ['z order', 'front', 'top'],
    category: 'Arrange',
    icon: 'MousePointer',
    execute: ({ applyZOrder }) => applyZOrder('front'),
    requiresDoc: true,
  },
  {
    id: 'zorder.back',
    label: 'Send To Back',
    keywords: ['z order', 'back', 'bottom'],
    category: 'Arrange',
    icon: 'MousePointer',
    execute: ({ applyZOrder }) => applyZOrder('back'),
    requiresDoc: true,
  },
  {
    id: 'veteran.evidence.build',
    label: 'Build Evidence Packet',
    keywords: ['evidence', 'packet', 'va claim', 'bundle'],
    category: 'Veteran',
    icon: 'FileSearch',
    execute: ({ setActiveWorkflow }) => setActiveWorkflow('evidence-builder'),
  },
  {
    id: 'veteran.dd214.parse',
    label: 'Analyze DD214',
    keywords: ['dd214', 'discharge', 'analyze', 'parse'],
    category: 'Veteran',
    icon: 'FileSearch',
    execute: ({ runDD214Analysis }) => runDD214Analysis(),
    requiresDoc: true,
  },
  {
    id: 'veteran.redact.pii',
    label: 'Auto-Redact PII',
    keywords: ['redact', 'pii', 'ssn', 'privacy'],
    category: 'Veteran',
    icon: 'ShieldOff',
    execute: ({ runAutoRedact }) => runAutoRedact(),
    requiresDoc: true,
  },
  {
    id: 'profile.edit',
    label: 'Edit Veteran Profile',
    keywords: ['profile', 'veteran', 'auto fill', 'settings'],
    category: 'Veteran',
    icon: 'MousePointer',
    execute: ({ openProfile }) => openProfile(),
  },
  {
    id: 'profile.autofill',
    label: 'Auto-fill Form Fields',
    keywords: ['auto fill', 'autofill', 'forms'],
    category: 'Veteran',
    icon: 'MousePointer',
    execute: ({ autoFillProfile }) => autoFillProfile(),
    requiresDoc: true,
  },
];
